services:
  - type: web
    name: emotion-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: FER_ONNX_PATH
        value: models/emotion-ferplus-8.onnx
      - key: HAAR_PATH
        value: data/haarcascade_frontalface_default.xml
    autoDeploy: true
